import type { RuntimeExperience, RuntimePlacement } from "../content/runtime-experience";

const asset = (id: string, kind: "scene" | "character" | "weather" | "item" | "animal", file: string) => ({
  id,
  kind,
  loadType: "image" as const,
  uri: `/imagegen/${file}`,
});

const landscapePlacements: RuntimePlacement[] = [
  { id: "land-wall-left", type: "asset", assetId: "concept-side-wall-canonical-v2", layer: "background", position: { x: 0.5, y: 0.5 }, scale: 1, depth: 0, projection: { mode: "clip", ref: "wall-left", sourceRect: { x: 0, y: 0, width: 384, height: 1024 } } },
  { id: "land-wall-center", type: "asset", assetId: "concept-wall-center", layer: "background", position: { x: 0.5, y: 0.5 }, scale: 1, depth: 1 },
  { id: "land-wall-right", type: "asset", assetId: "concept-side-wall-canonical-v2", layer: "background", position: { x: 0.5, y: 0.5 }, scale: 1, depth: 2, projection: { mode: "clip", ref: "wall-right", sourceRect: { x: 0, y: 0, width: 384, height: 1024 } } },
  { id: "land-fridge", type: "asset", assetId: "concept-fridge", layer: "background", position: { x: 0.3802, y: 0.2617 }, scale: 1, depth: 8 },
  { id: "land-oven", type: "asset", assetId: "concept-oven", layer: "background", position: { x: 0.744, y: 0.3301 }, scale: 0.8, depth: 9 },
  { id: "land-oven-tray", type: "asset", assetId: "oven-tray", layer: "stage", position: { x: 0.744, y: 0.5156 }, scale: 0.28, depth: 10 },
  { id: "land-oven-curtain", type: "asset", assetId: "concept-oven-curtain", layer: "stage", position: { x: 0.7566, y: 0.3665 }, scale: 1.064, depth: 11 },
  { id: "land-ceiling-fixture", type: "asset", assetId: "concept-ceiling-fixture", layer: "stage", position: { x: 0.5, y: 0.1045 }, scale: 1.2, depth: 12 },
  { id: "land-side-prop-left-pan-pair", type: "asset", assetId: "concept-side-prop-left-pan-pair-perspective", layer: "stage", position: { x: 0.06640625, y: 0.2503043945 }, scale: 0.6, depth: 13 },
  { id: "land-side-prop-left-utensil-rail", type: "asset", assetId: "concept-side-prop-left-utensil-rail-perspective", layer: "stage", position: { x: 0.0625, y: 0.3847045898 }, scale: 0.55, depth: 14 },
  { id: "land-side-prop-left-magnetic-knife-rack", type: "asset", assetId: "concept-side-prop-left-magnetic-knife-rack-perspective", layer: "stage", position: { x: 0.0625, y: 0.53271484375 }, scale: 0.5, depth: 15 },
  { id: "land-side-prop-right-tokyo-frame", type: "asset", assetId: "concept-side-prop-right-tokyo-frame-perspective", layer: "stage", position: { x: 0.927177, y: 0.25981525 }, scale: 0.48, depth: 16 },
  { id: "land-side-prop-right-melbourne-frame", type: "asset", assetId: "concept-side-prop-right-melbourne-frame-perspective", layer: "stage", position: { x: 0.927177, y: 0.38191375 }, scale: 0.48, depth: 16 },
  { id: "land-side-prop-right-plant-shelf", type: "asset", assetId: "concept-side-prop-right-plant-shelf-perspective", layer: "stage", position: { x: 0.927177, y: 0.4995963 }, scale: 0.45, depth: 17 },
  { id: "land-floor", type: "asset", assetId: "concept-floor-canonical-v3", layer: "foreground", position: { x: 0.5, y: 0.5 }, scale: 1, depth: 20, projection: { mode: "clip", ref: "floor", sourceRect: { x: 0, y: 0, width: 1536, height: 512 }, clipPolygon: [{ x: 0, y: 968 }, { x: 192, y: 826 }, { x: 1354, y: 832 }, { x: 1536, y: 968 }, { x: 1536, y: 1024 }, { x: 0, y: 1024 }], uvInsetX: 0.05 } },
  { id: "land-counter-base", type: "asset", assetId: "concept-counter-base", layer: "stage", position: { x: 0.5, y: 0.7139 }, scale: 1, depth: 30 },
  { id: "land-counter-top", type: "asset", assetId: "concept-counter-top", layer: "stage", position: { x: 0.4967, y: 0.5654 }, scale: 1, depth: 31 },
  { id: "land-mixer", type: "asset", assetId: "concept-mixer", layer: "stage", position: { x: 0.2279, y: 0.498 }, scale: 0.5, depth: 32 },
  { id: "land-display-cabinet", type: "asset", assetId: "concept-display-cabinet", layer: "stage", position: { x: 0.5973, y: 0.4365 }, scale: 1, depth: 33 },
  { id: "land-pandan-pearl-sugar-choux", type: "spawn", spawnId: "pandan-pearl-sugar-choux", assetId: "pastry-pandan-pearl-sugar-choux-landscape-v2", layer: "stage", position: { x: 0.50382, y: 0.52219 }, scale: 0.34, depth: 34 },
  { id: "land-pandan-thai-tea-saint-honore", type: "spawn", spawnId: "pandan-thai-tea-saint-honore", assetId: "pastry-pandan-thai-tea-saint-honore-landscape-v2", layer: "stage", position: { x: 0.54243, y: 0.52219 }, scale: 0.34, depth: 34 },
  { id: "land-pandan-thai-tea-saint-honore-6-inch", type: "spawn", spawnId: "pandan-thai-tea-saint-honore-6-inch", assetId: "pastry-pandan-thai-tea-saint-honore-6-inch-landscape-v2", layer: "stage", position: { x: 0.59159, y: 0.52219 }, scale: 0.34, depth: 34 },
  { id: "land-pistachio-cherry-tart", type: "spawn", spawnId: "pistachio-cherry-tart", assetId: "pastry-pistachio-cherry-tart-landscape-v2", layer: "stage", position: { x: 0.63645, y: 0.52219 }, scale: 0.34, depth: 34 },
  { id: "land-muscat-white-wine", type: "spawn", spawnId: "muscat-white-wine", assetId: "pastry-muscat-white-wine-landscape-v2", layer: "stage", position: { x: 0.67199, y: 0.52219 }, scale: 0.34, depth: 34 },
  { id: "land-pandan-thai-tea-cake-roll", type: "spawn", spawnId: "pandan-thai-tea-cake-roll", assetId: "pastry-pandan-thai-tea-cake-roll-landscape-v2", layer: "stage", position: { x: 0.50367, y: 0.5759 }, scale: 0.34, depth: 34 },
  { id: "land-vanilla-basque-cheesecake-slice", type: "spawn", spawnId: "vanilla-basque-cheesecake-slice", assetId: "pastry-vanilla-basque-cheesecake-slice-landscape-v2", layer: "stage", position: { x: 0.54152, y: 0.5759 }, scale: 0.34, depth: 34 },
  { id: "land-vanilla-basque-cheesecake-6-inch", type: "spawn", spawnId: "vanilla-basque-cheesecake-6-inch", assetId: "pastry-vanilla-basque-cheesecake-6-inch-landscape-v2", layer: "stage", position: { x: 0.58979, y: 0.5759 }, scale: 0.34, depth: 34 },
  { id: "land-pandan-madeleine-2-pack", type: "spawn", spawnId: "pandan-madeleine-2-pack", assetId: "pastry-pandan-madeleine-2-pack-landscape-v2", layer: "stage", position: { x: 0.6355, y: 0.5759 }, scale: 0.34, depth: 34 },
  { id: "land-pistachio-cherry-dacquoise", type: "spawn", spawnId: "pistachio-cherry-dacquoise", assetId: "pastry-pistachio-cherry-dacquoise-landscape-v2", layer: "stage", position: { x: 0.66893, y: 0.5759 }, scale: 0.34, depth: 34 },
  { id: "land-vanilla-canele", type: "spawn", spawnId: "vanilla-canele", assetId: "pastry-vanilla-canele-landscape-v2", layer: "stage", position: { x: 0.69628, y: 0.5759 }, scale: 0.34, depth: 34 },
  { id: "land-calendar", type: "spawn", spawnId: "calendar", layer: "stage", position: { x: 0.2539, y: 0.3271 }, scale: 0.18, depth: 35 },
  { id: "land-menu", type: "spawn", spawnId: "menu-board", assetId: "menu-clipboard-landscape", layer: "foreground", position: { x: 0.2018229167, y: 0.3271484375 }, scale: 0.18, depth: 36 },
  { id: "land-stool-1", type: "asset", assetId: "concept-stool", layer: "foreground", position: { x: 0.181, y: 0.8135 }, scale: 0.49, depth: 40 },
  { id: "land-stool-2", type: "asset", assetId: "concept-stool", layer: "foreground", position: { x: 0.2806, y: 0.8135 }, scale: 0.49, depth: 40 },
  { id: "land-stool-3", type: "asset", assetId: "concept-stool", layer: "foreground", position: { x: 0.3802, y: 0.8135 }, scale: 0.49, depth: 40 },
  { id: "land-stool-4", type: "asset", assetId: "concept-stool", layer: "foreground", position: { x: 0.4798, y: 0.8135 }, scale: 0.49, depth: 40 },
  { id: "land-stool-5", type: "asset", assetId: "concept-stool", layer: "foreground", position: { x: 0.5794, y: 0.8135 }, scale: 0.49, depth: 40 },
  { id: "land-stool-6", type: "asset", assetId: "concept-stool", layer: "foreground", position: { x: 0.679, y: 0.8135 }, scale: 0.49, depth: 40 },
  { id: "land-cat", type: "spawn", spawnId: "cat-landscape", layer: "foreground", position: { x: 0.835, y: 0.8894 }, scale: 0.36, depth: 52 },
];

const portraitPlacements: RuntimePlacement[] = [
  { id: "port-wall", type: "asset", assetId: "concept-wall-center", layer: "background", position: { x: 0.5, y: 0.5 }, scale: 1, depth: 0 },
  { id: "port-floor", type: "asset", assetId: "concept-floor-canonical-v3", layer: "foreground", position: { x: 0.5, y: 0.8 }, scale: 1, depth: 20 },
  { id: "port-counter", type: "asset", assetId: "concept-counter-base", layer: "stage", position: { x: 0.5, y: 0.7 }, scale: 1, depth: 30 },
];

const demoExperience = {
  schemaVersion: 3,
  mode: "demo",
  release: { id: "goody-demo", version: "2.0.0" },
  assets: [
    asset("concept-side-wall-canonical-v2", "scene", "goody-side-wall-canonical-v2.png"),
    asset("concept-floor-canonical-v3", "scene", "goody-floor-canonical-v3.png"),
    asset("concept-side-prop-left-pan-pair-perspective", "item", "goody-side-prop-left-pan-pair-perspective-v1.png"),
    asset("concept-side-prop-left-utensil-rail-perspective", "item", "goody-side-prop-left-utensil-rail-perspective-v1.png"),
    asset("concept-side-prop-left-magnetic-knife-rack-perspective", "item", "goody-side-prop-left-magnetic-knife-rack-perspective-v1.png"),
    asset("concept-side-prop-right-tokyo-frame-perspective", "item", "goody-side-prop-right-tokyo-frame-perspective-v1.png"),
    asset("concept-side-prop-right-melbourne-frame-perspective", "item", "goody-side-prop-right-melbourne-frame-perspective-v1.png"),
    asset("concept-side-prop-right-plant-shelf-perspective", "item", "goody-side-prop-right-plant-shelf-perspective-v1.png"),
    asset("concept-wall-center", "scene", "goody-scene-landscape-concept-center-wall-v1.png"),
    asset("concept-fridge", "scene", "goody-appliance-fridge-concept-v1.png"),
    asset("concept-oven", "scene", "goody-appliance-oven-concept-v1.png"),
    asset("concept-counter-base", "scene", "goody-counter-base-concept-v1.png"),
    asset("concept-counter-top", "scene", "goody-counter-top-concept-v1.png"),
    asset("concept-display-cabinet", "item", "goody-counter-display-concept-v1.png"),
    asset("concept-stool", "item", "goody-item-stool-concept-v1.png"),
    asset("concept-mixer", "item", "goody-item-mixer-concept-v1.png"),
    asset("concept-oven-curtain", "item", "goody-item-oven-curtain-concept-v1.png"),
    asset("concept-ceiling-fixture", "item", "goody-item-ceiling-fixture-concept-v1.png"),
    asset("oven-tray", "item", "goody-item-oven-tray-v1.png"),
    asset("pastry-pandan-pearl-sugar-choux-landscape-v2", "item", "goody-pastry-pandan-pearl-sugar-choux-landscape-v2.png"),
    asset("pastry-pandan-thai-tea-saint-honore-landscape-v2", "item", "goody-pastry-pandan-thai-tea-saint-honore-landscape-v2.png"),
    asset("pastry-pandan-thai-tea-saint-honore-6-inch-landscape-v2", "item", "goody-pastry-pandan-thai-tea-saint-honore-6-inch-landscape-v2.png"),
    asset("pastry-pistachio-cherry-tart-landscape-v2", "item", "goody-pastry-pistachio-cherry-tart-landscape-v2.png"),
    asset("pastry-muscat-white-wine-landscape-v2", "item", "goody-pastry-muscat-white-wine-landscape-v2.png"),
    asset("pastry-pandan-thai-tea-cake-roll-landscape-v2", "item", "goody-pastry-pandan-thai-tea-cake-roll-landscape-v2.png"),
    asset("pastry-vanilla-basque-cheesecake-slice-landscape-v2", "item", "goody-pastry-vanilla-basque-cheesecake-slice-landscape-v2.png"),
    asset("pastry-vanilla-basque-cheesecake-6-inch-landscape-v2", "item", "goody-pastry-vanilla-basque-cheesecake-6-inch-landscape-v2.png"),
    asset("pastry-pandan-madeleine-2-pack-landscape-v2", "item", "goody-pastry-pandan-madeleine-2-pack-landscape-v2.png"),
    asset("pastry-pistachio-cherry-dacquoise-landscape-v2", "item", "goody-pastry-pistachio-cherry-dacquoise-landscape-v2.png"),
    asset("pastry-vanilla-canele-landscape-v2", "item", "goody-pastry-vanilla-canele-landscape-v2.png"),
    {
      id: "shopkeeper-animated",
      kind: "character",
      loadType: "spritesheet",
      uri: "/imagegen/goody-character-shopkeeper-8f-v1.png",
      frame: { width: 512, height: 768 },
      frameCount: 8,
      animations: [
        { id: "idle", frames: [0, 1, 2, 3], frameRate: 3, repeat: -1, repeatDelayMs: 900 },
        { id: "moving", frames: [4, 5, 6, 7], frameRate: 8, repeat: -1 },
      ],
    },
    {
      id: "cat-animated",
      kind: "animal",
      loadType: "spritesheet",
      uri: "/imagegen/goody-animal-cat-8f-v1.png",
      frame: { width: 512, height: 384 },
      frameCount: 8,
      animations: [
        { id: "idle", frames: [0, 1, 2, 3, 4, 5, 6, 7], frameRate: 5, repeat: -1, repeatDelayMs: 1000 },
      ],
    },
    asset("calendar-sprite", "item", "goody-item-calendar-v1.png"),
    asset("menu-clipboard-landscape", "item", "goody-item-menu-clipboard-landscape-v1.png"),
  ],
  layouts: {
    landscape: {
      world: { width: 1536, height: 1024 },
      player: {
        spawnId: "player-landscape",
        position: { x: 0.79, y: 0.58 },
        movementBounds: { minX: 0.176, maxX: 0.82, minY: 0.56, maxY: 0.58 },
        scale: 0.81,
        depth: 29,
      },
      projections: [
        {
          id: "wall-left",
          kind: "projective-quad",
          localSize: { width: 384, height: 1024 },
          corners: [{ x: 0, y: 0 }, { x: 192, y: 0 }, { x: 192, y: 826 }, { x: 0, y: 968 }],
          horizontalGuides: [{ localY: 672, left: { x: 0, y: 674 }, right: { x: 192, y: 613 } }],
          subdivisions: { x: 4, y: 16 },
        },
        {
          id: "wall-right",
          kind: "projective-quad",
          localSize: { width: 384, height: 1024 },
          corners: [{ x: 1354, y: 0 }, { x: 1536, y: 0 }, { x: 1536, y: 968 }, { x: 1354, y: 832 }],
          horizontalGuides: [{ localY: 672, left: { x: 1354, y: 613 }, right: { x: 1536, y: 674 } }],
          subdivisions: { x: 4, y: 16 },
        },
        {
          id: "floor",
          kind: "projective-quad",
          localSize: { width: 1536, height: 512 },
          corners: [{ x: 192, y: 826 }, { x: 1354, y: 832 }, { x: 1536, y: 1024 }, { x: 0, y: 1024 }],
          subdivisions: { x: 4, y: 16 },
        },
      ],
      placements: landscapePlacements,
    },
    portrait: {
      world: { width: 1086, height: 1448 },
      player: {
        spawnId: "player-landscape",
        position: { x: 0.5, y: 0.79 },
        movementBounds: { minX: 0.12, maxX: 0.88, minY: 0.64, maxY: 0.89 },
        scale: 0.27,
        depth: 50,
      },
      projections: [],
      placements: portraitPlacements,
    },
  },
  spawns: {
    characters: [
      {
        id: "player-landscape",
        kind: "character",
        assetId: "shopkeeper-animated",
        controllable: true,
        animation: {
          defaultClip: "idle",
          movingClip: "moving",
          autoplay: true,
          flipWithMovement: true,
          movementThreshold: 0.1,
          stopDelayMs: 120,
        },
      },
    ],
    animals: [
      {
        id: "cat-landscape",
        kind: "animal",
        assetId: "cat-animated",
        animation: { defaultClip: "idle", autoplay: true },
      },
    ],
    items: [
      { id: "calendar", kind: "item", assetId: "calendar-sprite" },
      { id: "menu-board", kind: "item", assetId: "menu-clipboard-landscape" },
      { id: "pandan-pearl-sugar-choux", kind: "item", assetId: "pastry-pandan-pearl-sugar-choux-landscape-v2" },
      { id: "pandan-thai-tea-saint-honore", kind: "item", assetId: "pastry-pandan-thai-tea-saint-honore-landscape-v2" },
      { id: "pandan-thai-tea-saint-honore-6-inch", kind: "item", assetId: "pastry-pandan-thai-tea-saint-honore-6-inch-landscape-v2" },
      { id: "pistachio-cherry-tart", kind: "item", assetId: "pastry-pistachio-cherry-tart-landscape-v2" },
      { id: "muscat-white-wine", kind: "item", assetId: "pastry-muscat-white-wine-landscape-v2" },
      { id: "pandan-thai-tea-cake-roll", kind: "item", assetId: "pastry-pandan-thai-tea-cake-roll-landscape-v2" },
      { id: "vanilla-basque-cheesecake-slice", kind: "item", assetId: "pastry-vanilla-basque-cheesecake-slice-landscape-v2" },
      { id: "vanilla-basque-cheesecake-6-inch", kind: "item", assetId: "pastry-vanilla-basque-cheesecake-6-inch-landscape-v2" },
      { id: "pandan-madeleine-2-pack", kind: "item", assetId: "pastry-pandan-madeleine-2-pack-landscape-v2" },
      { id: "pistachio-cherry-dacquoise", kind: "item", assetId: "pastry-pistachio-cherry-dacquoise-landscape-v2" },
      { id: "vanilla-canele", kind: "item", assetId: "pastry-vanilla-canele-landscape-v2" },
    ],
  },
  actions: [],
  weather: {
    defaultTone: "sunny",
    presentations: [
      { tone: "sunny", tint: "#fff2c6" },
      { tone: "cloudy", tint: "#c7d0cf" },
      { tone: "rain", tint: "#9ebbc4" },
      { tone: "storm", tint: "#687d8b" },
      { tone: "fog", tint: "#d9dfdb" },
    ],
  },
  interactions: [
    {
      id: "open-calendar",
      triggers: [
        { type: "click", targetId: "calendar" },
        { type: "keyboard", key: "C", targetId: "calendar" },
      ],
      action: { type: "open-modal", panel: "calendar", payloadKey: "goody-calendar" },
    },
    {
      id: "open-weekly-menu",
      triggers: [
        { type: "click", targetId: "menu-board" },
        { type: "keyboard", key: "M", targetId: "menu-board" },
      ],
      action: { type: "open-modal", panel: "weekly-menu", payloadKey: "goody-weekly-menu" },
    },
  ],
  modalPayloads: [
    {
      key: "goody-calendar",
      panel: "calendar",
      title: "店裡月曆",
      schedule: {
        timeZone: "Asia/Taipei",
        entries: [
          { days: ["Monday"], state: "closed", note: "固定休息" },
          { days: ["Tuesday", "Wednesday", "Thursday"], state: "prep", note: "備料日" },
          { days: ["Friday", "Saturday", "Sunday"], state: "open", hours: "13:00-18:00" },
        ],
      },
    },
    {
      key: "goody-weekly-menu",
      panel: "weekly-menu",
      title: "本週甜點",
      weekOf: "2026-07-27",
      dateRange: {
        start: "2026-07-31",
        end: "2026-08-02",
        label: "07/31(五)－08/02(日)",
      },
      hours: "13:00-18:00",
      items: [
        { sku: "01", name: "斑蘭珍珠糖泡芙", priceTwd: 120, badges: ["新品"] },
        { sku: "02", name: "斑蘭泰奶聖多諾", priceTwd: 220, notes: ["建議當天吃完"] },
        { sku: "03", name: "斑蘭泰奶聖多諾 6吋", priceTwd: 1300, notes: ["建議當天吃完"] },
        { sku: "04", name: "開心果櫻桃塔", priceTwd: 220 },
        { sku: "05", name: "麝香白酒", priceTwd: 200, notes: ["含酒"] },
        { sku: "06", name: "斑蘭泰奶蛋糕捲", priceTwd: 450 },
        { sku: "07", name: "香草巴斯克乳酪 切片", priceTwd: 130 },
        { sku: "08", name: "香草巴斯克乳酪 6吋", priceTwd: 750 },
        { sku: "09", name: "斑蘭瑪德蓮 2入", priceTwd: 100 },
        { sku: "10", name: "開心果櫻桃達克瓦茲", priceTwd: 90 },
        { sku: "11", name: "香草可麗露", priceTwd: 80 },
      ],
    },
  ],
} satisfies RuntimeExperience;

export function getDemoRuntimeExperience(): RuntimeExperience {
  return JSON.parse(JSON.stringify(demoExperience)) as RuntimeExperience;
}
